port: 1234
hooks:

  - name: Shell hook
    regexp: .*custom.*
    shell: echo customdata

  - name: Url hook
    regexp: .*url\/(.*)$
    url: http://localhost:8000/fixtures/$1

  - name: File hook
    regexp: ^.*$
    file: ./$0
