port: 1234
# user: hooktftp
hooks:

  - type: shell
    description: Shell hook
    regexp: .*custom.*
    template: echo customdata

  - type: url
    description: Url hook
    regexp: .*url\/(.*)$
    template: http://localhost:8000/fixtures/$1

  - type: file
    description: File hook
    regexp: ^.*$
    template: ./$0
